package io.nats.java.internal.actions.client;


import io.nats.java.internal.Action;
import io.nats.java.internal.NATSProtocolVerb;

/**
 * This is sent from the client to the server to subscribe to a subject.
 * Description
 * SUB initiates a subscription to a subject, optionally joining a distributed queue group.
 * Syntax
 * <p>
 * SUB <subject> [queue group] <sid>\r\n
 * <p>
 * where:
 * subject: The subject name to subscribe to
 * queue group: If specified, the subscriber will join this queue group
 * sid: A unique alphanumeric subscription ID, generated by the client
 */
public class Subscribe implements Action {
    private final String subject; // subject: The subject name to subscribe to
    private final String queueGroup; //queueGroup: If specified, the subscriber will join this queue group
    private final String sid; // sid: A unique alphanumeric subscription ID, generated by the client

    public Subscribe(String subject, String queueGroup, String sid) {
        this.subject = subject;
        this.queueGroup = queueGroup;
        this.sid = sid;
    }

    @Override
    public NATSProtocolVerb verb() {
        return NATSProtocolVerb.SUBSCRIBE;
    }



}
